#!/bin/sh

exec hugo server \
  --baseURL=${HUGO_BASE_URL:-http://mifo.sk} \
  --theme ${HUGO_THEME:-slim} \
  --bind=0.0.0.0 \
  --port=8080 \
  --disableLiveReload=true \
  --watch=false \
  --appendPort=false \
  --verbose \
  --log

